#!/usr/bin/env python

"""
Sample script for starting CryoConTempController server
"""

import os
import sys

SERVER_PATH = '/ds/python/CryoConTempController'

def main():
    tango_home = os.environ['TANGO_HOME']
    path =  tango_home + SERVER_PATH
    sys.path.insert(0,path)
    import CryoConTempController
    CryoConTempController.main(sys.argv)

if __name__ == '__main__':
    main()
