{% set name = "cryocon" %}
{% set version = "3.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../..

build:
  number: 0
  noarch: python
  entry_points:
    - CryoConTempController = cryocon.tango:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - pytango >=9.2.5
    - python >=3.5
    - sockio >=0.8.1
  run:
    - pip
    - pytango >=9.2.5
    - python >=3.5
    - sockio >=0.8.1

test:
  imports:
    - cryocon

about:
  home: "http://www.github.com/tiagocoutinho/cryocon"
  license: "GNU Library or Lesser General Public (LGPL)"
  license_family: LGPL
  license_file: 
  summary: "CryoCon temperature library and tango device server"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
